version: "3.8"
services:
  db:
    container_name: foodbudget-db
    image: postgres:12.4
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: foodbudget
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  foodbudget_api:
    image: foodbudget_api:1.0.0
    env_file:
      - .env
    # depends_on:
    #   - foodbudget-db
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: ./packages/@foodbudget/backend/api/Dockerfile
    # volumes:
    #   - ./:/src/app
