version: "3.8"
services:
  foodbudget-db:
    container_name: foodbudget-db
    image: postgres:12.4
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: foodbudget
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - foodbudget-db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pwdpwd
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
  # web:
  #   env_file:
  #     - .env
  #   depends_on:
  #     - foodbudget-db
  #   ports:
  #     - 8080:8080
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./:/src/app
  # crondb:
  #   image: mongo:3.6
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: pass
  #   ports:
  #     - "27017:27017"
