version: '3.8'
services:
  foodbudget-db:
    container_name: foodbudget-db
    image: postgres:12.4
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: foodbudget
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  foodbudget-api:
    image: foodbudget-prod-api:latest
    container_name: foodbudget-prod-api
    env_file:
      - .env
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: ./packages/@foodbudget/backend/api/Dockerfile

  foodbudget-jobs:
    image: foodbudget-jobs:latest
    container_name: foodbudget-jobs
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./packages/@foodbudget/backend/jobs/Dockerfile

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pwdpwd
    ports:
      - "5050:80"
