version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.12.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  lint:
    docker:
      - image: circleci/node:14.12.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - add_ssh_keys:
          fingerprints:
            - "27:cc:f8:7a:36:04:b8:63:b5:8f:4d:7f:ad:8a:97:4b"
      - run: yarn lint
  test:
    docker:
      - image: circleci/node:14.12.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - add_ssh_keys:
          fingerprints:
            - "27:cc:f8:7a:36:04:b8:63:b5:8f:4d:7f:ad:8a:97:4b"
      - run: yarn test
  release:
    docker:
      - image: circleci/node:14.12.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - add_ssh_keys:
          fingerprints:
            - "27:cc:f8:7a:36:04:b8:63:b5:8f:4d:7f:ad:8a:97:4b"
      - run: git config --global user.email "thefoodbudget@gmail.com"
      - run: git config --global user.name "Food Budget"
      - run: yarn release
      - run: git push --follow-tags origin master
workflows:
  version: 2
  verify:
    jobs:
      - build
      - lint:
          requires:
          - build
      - test:
          requires:
          - build
      - release:
          filters:
            branches:
              only: master
          requires:
            - lint
            - test
