version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.11.0-browsers
    steps:
      - checkout
      - create_concatenated_yarn_lock:
          filename: combined-yarn-lock.txt
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "combined-yarn-lock.txt" }}
            - v1-dependencies-transpiled-files
      - run: yarn
      - save_cache:
          paths:
            - node_modules
            - packages/@foodbudget/api/node_modules
            - packages/@foodbudget/email/node_modules
            # - packages/@foodbudget/errors/node_modules
            - packages/@foodbudget/jobs/node_modules
            # - packages/@foodbudget/logger/node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "combined-yarn-lock.txt" }}
  transpile:
    docker:
      - image: circleci/node:14.11.0-browsers
    steps:
      - checkout
      - create_concatenated_yarn_lock:
          filename: combined-yarn-lock.txt
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "combined-yarn-lock.txt" }}
            - v1-dependencies-transpiled-files
      - run: yarn build
      - save_cache:
            paths:
              - packages/@foodbudget/api/dist
              - packages/@foodbudget/email/dist
              - packages/@foodbudget/errors/dist
              - packages/@foodbudget/jobs/dist
              - packages/@foodbudget/logger/dist
            key: v1-dependencies-transpiled-files
  lint:
    docker:
      - image: circleci/node:14.11.0-browsers
    steps:
      - checkout
      - create_concatenated_yarn_lock:
          filename: combined-yarn-lock.txt
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "combined-yarn-lock.txt" }}
            - v1-dependencies-transpiled-files
      - add_ssh_keys:
          fingerprints:
            - "27:cc:f8:7a:36:04:b8:63:b5:8f:4d:7f:ad:8a:97:4b"
      - run: yarn lint
  unitTest:
    docker:
      - image: circleci/node:14.11.0-browsers
    steps:
      - checkout
      - create_concatenated_yarn_lock:
          filename: combined-yarn-lock.txt
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "combined-yarn-lock.txt" }}
            - v1-dependencies-transpiled-files
      - add_ssh_keys:
          fingerprints:
            - "27:cc:f8:7a:36:04:b8:63:b5:8f:4d:7f:ad:8a:97:4b"
      - run: yarn test:unit
  integrationTest:
    docker:
      - image: circleci/node:14.11.0-browsers
    steps:
      - checkout
      - create_concatenated_yarn_lock:
          filename: combined-yarn-lock.txt
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "combined-yarn-lock.txt" }}
            - v1-dependencies-transpiled-files
      - add_ssh_keys:
          fingerprints:
            - "27:cc:f8:7a:36:04:b8:63:b5:8f:4d:7f:ad:8a:97:4b"
      - run: yarn test:integration      
  release:
    docker:
      - image: circleci/node:14.11.0-browsers
    steps:
      - checkout
      - create_concatenated_yarn_lock:
          filename: combined-yarn-lock.txt
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "combined-yarn-lock.txt" }}
            - v1-dependencies-transpiled-files
      - add_ssh_keys:
          fingerprints:
            - "27:cc:f8:7a:36:04:b8:63:b5:8f:4d:7f:ad:8a:97:4b"
      - run: git config --global user.email "thefoodbudget@gmail.com"
      - run: git config --global user.name "Food Budget"
      - run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > ~/repo/.npmrc
      - run: yarn release
      - run: git push --follow-tags origin master
commands:
  create_concatenated_yarn_lock:
    description: "Concatenate all yarn.lock files recognized by lerna.js into single file. File is used as checksum source for part of caching key."
    parameters:
      filename:
        type: string
    steps:
      - run:
          name: Combine yarn.lock files to single file
          # command: npx lerna la -a | awk -F packages '{printf "\"packages%s/yarn.lock\" ", $2}' | xargs ls -d 2> /dev/null | xargs cat > << parameters.filename >>
          command: echo packages/@foodbudget/api/yarn.lock | xargs cat > << parameters.filename >>
workflows:
  version: 2
  verify:
    jobs:
      - build
      - transpile:
         requires:
          - build
      - lint:
          requires:
          - transpile
      - unitTest:
          requires:
          - transpile
      - integrationTest:
          requires:
          - transpile
      - release:
          filters:
            branches:
              only: master
          requires:
            - lint
            - unitTest
            - integrationTest
