version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.11.0-browsers
    steps:
      - checkout
      - create_concatenated_yarn_lock:
          filename: combined-yarn-lock.txt
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "combined-yarn-lock.txt" }}
            - v1-dependencies
      - run: yarn
      - save_cache:
          paths:
            - node_modules
            - packages/@foodbudget/backend/api/node_modules
            - packages/@foodbudget/backend/email/node_modules
            # - packages/@foodbudget/errors/node_modules
            - packages/@foodbudget/backend/jobs/node_modules
            - packages/@foodbudget/frontend/node_modules
            # - packages/@foodbudget/logger/node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "combined-yarn-lock.txt" }}
  lint:
    docker:
      - image: circleci/node:14.11.0-browsers
    steps:
      - checkout
      - create_concatenated_yarn_lock:
          filename: combined-yarn-lock.txt
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "combined-yarn-lock.txt" }}
            - v1-dependencies
      - add_ssh_keys:
          fingerprints:
            - "27:cc:f8:7a:36:04:b8:63:b5:8f:4d:7f:ad:8a:97:4b"
      - run: yarn setup
      - run: yarn lint
  frontEndUnitTest:
    docker:
      - image: circleci/node:14.11.0-browsers
    steps:
      - checkout
      - create_concatenated_yarn_lock:
          filename: combined-yarn-lock.txt
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "combined-yarn-lock.txt" }}
            - v1-dependencies
      - add_ssh_keys:
          fingerprints:
            - "27:cc:f8:7a:36:04:b8:63:b5:8f:4d:7f:ad:8a:97:4b"
      - run: yarn setup:ui
      - run: yarn test:ui-ci
  backEndUnitTest:
    docker:
      - image: circleci/node:14.11.0-browsers
    steps:
      - checkout
      - create_concatenated_yarn_lock:
          filename: combined-yarn-lock.txt
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "combined-yarn-lock.txt" }}
            - v1-dependencies
      - add_ssh_keys:
          fingerprints:
            - "27:cc:f8:7a:36:04:b8:63:b5:8f:4d:7f:ad:8a:97:4b"
      - run: yarn setup:server
      - run: yarn test:server-ci
  backEndIntegrationTest:
    docker:
      - image: circleci/node:14.11.0-browsers
    steps:
      - checkout
      - create_concatenated_yarn_lock:
          filename: combined-yarn-lock.txt
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "combined-yarn-lock.txt" }}
            - v1-dependencies
      - add_ssh_keys:
          fingerprints:
            - "27:cc:f8:7a:36:04:b8:63:b5:8f:4d:7f:ad:8a:97:4b"
      - run: yarn setup:server
      - run: yarn int:server-ci
  release:
    docker:
      - image: circleci/node:14.11.0-browsers
    steps:
      - checkout
      - create_concatenated_yarn_lock:
          filename: combined-yarn-lock.txt
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "combined-yarn-lock.txt" }}
            - v1-dependencies
      - add_ssh_keys:
          fingerprints:
            - "27:cc:f8:7a:36:04:b8:63:b5:8f:4d:7f:ad:8a:97:4b"
      - run: git config --global user.email "thefoodbudget@gmail.com"
      - run: git config --global user.name "Food Budget"
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
      - run: npm get registry
      - run: npm whoami
      - run: yarn setup
      - run: yarn release
      - run: git push --follow-tags origin master
commands:
  create_concatenated_yarn_lock:
    description: "Concatenate all yarn.lock files recognized by lerna.js into single file. File is used as checksum source for part of caching key."
    parameters:
      filename:
        type: string
    steps:
      - run:
          name: Combine yarn.lock files to single file
          # command: npx lerna la -a | awk -F packages '{printf "\"packages%s/yarn.lock\" ", $2}' | xargs ls -d 2> /dev/null | xargs cat > << parameters.filename >>
          command: echo packages/@foodbudget/backend/api/yarn.lock | xargs cat > << parameters.filename >>
workflows:
  version: 2
  verify:
    jobs:
      - build
      - lint:
          requires:
          - build
      - frontEndUnitTest:
          requires:
          - build
      - backEndUnitTest:
          requires:
          - build
      - backEndIntegrationTest:
          requires:
          - build
      - release:
          filters:
            branches:
              only: master
          requires:
            - lint
            - frontEndUnitTest
            - backEndUnitTest
            - backEndIntegrationTest
