#! /bin/bash

echo EMAIL_SERVICE=$EMAIL_SERVICE >> .env
echo EMAIL_USER=$EMAIL_USER >> .env
echo EMAIL_PASSWORD=$EMAIL_PASSWORD >> .env
echo DATABASE_URL=$DATABASE_URL >> .env
echo TEST_DATABASE_URL=$TEST_DATABASE_URL >> .env
echo GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID >> .env
echo GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET >> .env
echo FACEBOOK_CLIENT_ID=$FACEBOOK_CLIENT_ID >> .env
echo FACEBOOK_CLIENT_SECRET=$FACEBOOK_CLIENT_SECRET >> .env
echo ACCESS_TOKEN_SECRET=$ACCESS_TOKEN_SECRET >> .env
echo ACCESS_TOKEN_EXPIRE_TIME_IN_MS=$ACCESS_TOKEN_EXPIRE_TIME_IN_MS >> .env
echo REFRESH_TOKEN_SECRET=$REFRESH_TOKEN_SECRET >> .env
echo REFRESH_TOKEN_EXPIRE_TIME_IN_MS=$REFRESH_TOKEN_EXPIRE_TIME_IN_MS >> .env
echo NPM_TOKEN=$NPM_TOKEN >> .env
echo LOG_LEVEL=$LOG_LEVEL >> .env